### ISSUE TITLE
[HATA] Iconlar yüklenmiyor

### ISSUE THREAD

**Issue by Sarperdgn** [IZM-Projects/izm-website#1]
![image](https://user-images.githubusercontent.com/51697170/103527532-8f85c600-4e93-11eb-9143-ff131784b2e5.png)

iconlar yüklenmiyor 

console: 
![image](https://user-images.githubusercontent.com/51697170/103527573-a0363c00-4e93-11eb-8035-42c50394013e.png)

**Comment by eggsy** [comment]
Bu hatayı mobil görünümde mi alıyorsunuz? Normal bir tarayıcıda telefon görünümünde veya telefon üzerinde bir tarayıcı telefon sürümünde bu sorunu görmüyoruz. Siz nerede alıyorsunuz bu hatayı, PWA içerisinde mi?

**Comment by Sarperdgn** [comment]
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0` üzerinden fazladan bi eklenti olmadan
`Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36` olarakda denedim aynı problem

**Comment by eggsy** [comment]
Sorunun nedenini hâlâ anlamamamla beraber sorunu araştırmaya devam edeceğim.
